### ISSUE TITLE
Only go results in metrics

### ISSUE THREAD

**Issue by lZzozZl** [hoomy-official/exporter-unifi-protect#4]
Does not show any information from the api.
i am running the exporter than pressing metrics and only see go_ metrics. No cameras, no nvr information is pulled/shown

**Comment by merlindorin** [comment]
Thank you for your feedback and sorry for the delay. This exporter is focused on my needs... e.g. having sensor data available.

Feel free to contribute and add more Unifi components.

ps: to prevent further mislead, I've updated the `Readme.md`. Again sorry about that.
